import img1 from "../../images/Logo.png";
import dior from "../../images/dior.jpg";

export const dummyData = [
    {
        title: "hello world",
        price: 578,
        imgUrl: img1,
        rating: 4, 
    },
    {
        title: "My Card",
        price: 320,
        imgUrl: img1,
        rating: 3,
    },
    {
        title: "Sauvage Dior",
        price: 847,
        imgUrl: dior,
        rating: 5,
    },
    {
        title: "My Card",
        price: 563,
        imgUrl: img1,
        rating: 2,
    },
    {
        title: "My Card",
        price: 5123,
        imgUrl: img1,
        rating: 1,
    },
    {
        title: "hello world",
        price: 578,
        imgUrl: img1,
        rating: 4,
    },
    {
        title: "My Card",
        price: 320,
        imgUrl: img1,
        rating: 3,
    },
    {
        title: "Sauvage Dior",
        price: 847,
        imgUrl: dior,
        rating: 5,
    },
    {
        title: "My Card",
        price: 563,
        imgUrl: img1,
        rating: 2,
    },
    {
        title: "My Card",
        price: 5123,
        imgUrl: img1,
        rating: 1,
    },
    {
        title: "hello world",
        price: 578,
        imgUrl: img1,
        rating: 4,
    },
    {
        title: "My Card",
        price: 320,
        imgUrl: img1,
        rating: 3,
    },
    {
        title: "Sauvage Dior",
        price: 847,
        imgUrl: dior,
        rating: 5,
    },
    {
        title: "My Card",
        price: 563,
        imgUrl: img1,
        rating: 2,
    },
    {
        title: "My Card",
        price: 5123,
        imgUrl: img1,
        rating: 1,
    },
    {
        title: "hello world",
        price: 578,
        imgUrl: img1,
        rating: 4,
    },
    {
        title: "My Card",
        price: 320,
        imgUrl: img1,
        rating: 3,
    },
    {
        title: "Sauvage Dior",
        price: 847,
        imgUrl: dior,
        rating: 5,
    },
    {
        title: "My Card",
        price: 563,
        imgUrl: img1,
        rating: 2,
    },
    {
        title: "My Card",
        price: 5123,
        imgUrl: img1,
        rating: 1,
    },
    {
        title: "hello world",
        price: 578,
        imgUrl: img1,
        rating: 4,
    },
    {
        title: "My Card",
        price: 320,
        imgUrl: img1,
        rating: 3,
    },
    {
        title: "Sauvage Dior",
        price: 847,
        imgUrl: dior,
        rating: 5,
    },
    {
        title: "My Card",
        price: 563,
        imgUrl: img1,
        rating: 2,
    },
    {
        title: "My Card",
        price: 5123,
        imgUrl: img1,
        rating: 1,
    },
    {
        title: "hello world",
        price: 578,
        imgUrl: img1,
        rating: 4,
    },
    {
        title: "My Card",
        price: 320,
        imgUrl: img1,
        rating: 3,
    },
    {
        title: "Sauvage Dior",
        price: 847,
        imgUrl: dior,
        rating: 5,
    },
    {
        title: "My Card",
        price: 563,
        imgUrl: img1,
        rating: 2,
    },
    {
        title: "My Card",
        price: 5123,
        imgUrl: img1,
        rating: 1,
    },
];
